### ISSUE TITLE
Simpler binding

### ISSUE THREAD

**Issue by tathanhdinh** [rust-xed/xed-sys#12]
Hello all,

In the current build script, I find that sometimes we need copy the source folders (i.e. `xed` and `mbuild`), that may be not necessary.

Could you please take a look at this [WIP branch](https://github.com/tathanhdinh/xed-sys-1/tree/binding-wip) which proposes a simpler build script.

Many thanks for any response.

**Comment by unterkontrolle** [comment]
Yeah, `build.rs` needs some love.

I'm totally in favor of what I've seen so far:
1. Checking if Python is installed, and issuing a proper error message if it's not.
2. Cleaning up the filesystem-related code.

We can also check the installed Python version matches XED build requirements. I would leave this for another discussion/PR though.

Maybe you want to do this work as a PR (to trigger CI runs).

**Comment by tathanhdinh** [comment]
Hi @unterkontrolle, thank you.

If you really want to take risk ;), then this is the PR #13.
