### ISSUE TITLE
Set up crate documentation

### ISSUE THREAD

**Issue by unterkontrolle** [rust-xed/xed-sys#16]
See https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field-optional

We need just an overall description, users should refer to original XED docs for details.

**Comment by Phantomical** [comment]
Currently we have a top level doc comment which becomes [this](https://docs.rs/xed-sys/0.2.3/xed_sys/).

It could definitely be expanded. However, I'm not sure what else we should put there.

**Comment by unterkontrolle** [comment]
Oh, I totally missed the doc comment.
I guess it's good enough for the time being.
