### ISSUE TITLE
[Discussion] Move all functions into the crate namespace?

### ISSUE THREAD

**Issue by Phantomical** [rust-xed/xed-sys#25]
Currently, we have two top-level modules: `xed_interface` and `xed_version`.
- `xed_version` contains `xed_get_version` and `xed_get_copyright`
- `xed_interface` contains _everything_. This includes `xed_get_version` and `xed_get_copyright`.

This is... not quite optimal. I propose that we simply export everything in the root module.

For backwards compatibility we need to keep the `xed_interface` and `xed_version` modules. However, they can be defined like this:
```
pub mod xed_interface {
    pub use crate::xed_interface_internal::*;
}
pub mod xed_version {
    pub use crate::{xed_get_version, xed_get_copyright};
}
```
where `xed_interface_internal` is wherever we actually import everything. This approach allows for the rustdoc to be nicer as well. Note that this approach ensures that we don't export `xed_interface::xed_interface::etc` which would be needlessly messy.

I wouldn't mark `xed_interface` and `xed_version` as deprecated just yet since that seems too quick to do in a single version bump. We can do that later whenever we feel like creating a 3.0 version.

Thoughts?

**Comment by agodnic** [comment]
> Currently, we have two top-level modules: `xed_interface` and `xed_version`.
> 
> * `xed_version` contains `xed_get_version` and `xed_get_copyright`
> * `xed_interface` contains _everything_. This includes `xed_get_version` and `xed_get_copyright`.
> 
> This is... not quite optimal. I propose that we simply export everything in the root module.
> 
> For backwards compatibility we need to keep the `xed_interface` and `xed_version` modules. However, they can be defined like this:
> 
> ```
> pub mod xed_interface {
>     pub use crate::xed_interface_internal::*;
> }
> pub mod xed_version {
>     pub use crate::{xed_get_version, xed_get_copyright};
> }
> ```
> 
> where `xed_interface_internal` is wherever we actually import everything. This approach allows for the rustdoc to be nicer as well. Note that this approach ensures that we don't export `xed_interface::xed_interface::etc` which would be needlessly messy.

Seems a cleaner design to me! I'm voting for this change.

> I wouldn't mark `xed_interface` and `xed_version` as deprecated just yet since that seems too quick to do in a single version bump. We can do that later whenever we feel like creating a 3.0 version.

Maybe we can update the underlying XED version, add this interface breaking change, and after that publish 3.0. I agree that none of these two features should be published as 0.2.x.
