### ISSUE TITLE
About crate ownership

### ISSUE THREAD

**Issue by unterkontrolle** [rust-xed/xed-sys#9]
The name `xed-sys` is already taken on crates.io, which is unfortunate.

I wonder if the owner @valarauca is interested in joining us to make a crates.io release with the name `xed-sys`. This way we would avoid creating unnecessary fragmentation in the Rust ecosystem.

If so, we'd have to:
*  Change this crate's name on Cargo.toml from `xed-sys2` to `xed-sys`.
*  Change this crate's version to a number strictly greater than the [current version on crates.io](https://crates.io/crates/xed-sys). I think it should be 0.2.0 since we'll introduce a breaking change in one way or another.

**Comment by valarauca** [comment]
I'll happily donate the name. Just not sure how to remove the old crate. 

(sorry for not replying to the email)

**Comment by Phantomical** [comment]
I don't believe it's necessary to remove the old crate. 

All that should be needed is to add either me or @unterkontrolle on as an owner to the package and then we can publish the updated version of xed-sys as version 0.2.

For reference, the instructions for addind/removing owners are [here](https://doc.rust-lang.org/cargo/reference/publishing.html).

**Comment by valarauca** [comment]
Thanks! I'll try to get this handed over to you shortly.

**Comment by valarauca** [comment]
I sent the support request. So hopefully the crates.io team can handle the transfer.

**Comment by unterkontrolle** [comment]
Thanks Cody!

I just invited Phantomical to be an owner.
After dealing with some PRs we'll be ready to publish 0.2.0.

**Comment by unterkontrolle** [comment]
Version [0.2](https://crates.io/crates/xed-sys) is published.
Thanks everyone!
